[package]
name = "win_pty"
version = "0.1.0"
edition = "2024"

[dependencies]
winapi = { version = "0.3.9", features = ["handleapi", "processthreadsapi", "winnt", "errhandlingapi", "accctrl", "aclapi", "securitybaseapi", "namedpipeapi"] }